### ISSUE TITLE
invalid-order-id: Parameter `order-id` is invalid

### ISSUE THREAD

**Issue by phantomk** [Computable-Finance/CoFiX-hedger#3]
```
com.huobi.exception.SDKException: [Executing] invalid-order-id: Parameter `order-id` is invalid.
	at com.huobi.service.huobi.connection.HuobiRestConnection.checkAndGetResponse(HuobiRestConnection.java:101)
	at com.huobi.service.huobi.connection.HuobiRestConnection.executeGetWithSignature(HuobiRestConnection.java:74)
	at com.huobi.service.huobi.HuobiTradeService.getOrder(HuobiTradeService.java:217)
	at io.cofix.hedging.utils.HuobiUtil.getOrder(HuobiUtil.java:16)
	at io.cofix.hedging.service.serviceImpl.TradeMarketServiceHuobiImpl.getOrderById(TradeMarketServiceHuobiImpl.java:37)
	at io.cofix.hedging.service.serviceImpl.HedgingJobServiceImpl.hedgingPool(HedgingJobServiceImpl.java:131)
	at io.cofix.hedging.service.serviceImpl.HedgingJobServiceImpl.hedging(HedgingJobServiceImpl.java:221)
	at io.cofix.hedging.vo.HedgingQuartzJob.executeInternal(HedgingQuartzJob.java:25)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
```

**Comment by obeey** [comment]
1.0.3 maybe fix this issue.
