### ISSUE TITLE
hedgingPool.getOrderId() is null, throw error

### ISSUE THREAD

**Issue by phantomk** [Computable-Finance/CoFiX-hedger#4]
```
2020-10-14 15:30:09 [ERROR] - Job hedging-jobs.418c36f0-e63f-40ff-9989-4cd1980e8198 threw an unhandled Exception: 
java.lang.NullPointerException: null
	at io.cofix.hedging.service.serviceImpl.HedgingJobServiceImpl.hedgingPool(HedgingJobServiceImpl.java:127)
	at io.cofix.hedging.service.serviceImpl.HedgingJobServiceImpl.hedging(HedgingJobServiceImpl.java:217)
	at io.cofix.hedging.vo.HedgingQuartzJob.executeInternal(HedgingQuartzJob.java:25)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2020-10-14 15:30:09 [ERROR] - Job (hedging-jobs.418c36f0-e63f-40ff-9989-4cd1980e8198 threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.NullPointerException: null
	at io.cofix.hedging.service.serviceImpl.HedgingJobServiceImpl.hedgingPool(HedgingJobServiceImpl.java:127)
	at io.cofix.hedging.service.serviceImpl.HedgingJobServiceImpl.hedging(HedgingJobServiceImpl.java:217)
	at io.cofix.hedging.vo.HedgingQuartzJob.executeInternal(HedgingQuartzJob.java:25)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 common frames omitted
```

**Comment by obeey** [comment]
Please use 1.0.3
